<%_ if (repoType == "private") { _%>
apiVersion: v1
kind: Secret
metadata:
  name: git-sshkey-secret
  namespace: <%= namespaceName %>
data:
  id_rsa: <%= deployKey %>
  config: <%= sshConfig %>
---
<%_ } _%>
apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: <%= namespaceName %>
data:
  .dockerconfigjson: <%= dockerConfig %>
type: kubernetes.io/dockerconfigjson