apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trggrt-push-trigger-binding${TOKEN}
  namespace: ferferfe
spec:
  params:
    - name: repo-url
      value: github.com/$(body.repository.full_name).git
    - name: revision
      value: $(body.head_commit.id)
    - name: author
      value: $(body.head_commit.author.name)
    - name: submodules
      value: "false"
    - name: git-branch
      value: $(body.ref)    
    - name: image-reference
      value: grewge   
    - name: clone-dir
      value: $(body.repository.full_name)   

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trggrt-push-trigger-template
  namespace: ferferfe
spec:
  params:
    - name: repo-url
    - name: revision
      default: main
    - name: submodules
    - name: git-branch
    - name: author
    - name: image-reference
    - name: clone-dir
    

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: trggrt-push-trigger-run-
      spec:
        serviceAccountName: tekton-service-account
        pipelineRef:
          name: trggrt-pipeline
        podTemplate:
          securityContext:
            fsGroup: 65532
        workspaces:
          - name: shared-data
            persistentVolumeClaim:
              claimName: tekton-pvc
          - name: github-secret
            secret:
              secretName: github-secret
          - name: docker-credentials
            secret:
              secretName: docker-credentials
        params:
          - name: repo-url
            value: $(tt.params.repo-url)
          - name: revision
            value: $(tt.params.revision)
          - name: submodules
            value: $(tt.params.submodules)
          - name: image-reference
            value: $(tt.params.image-reference)
          - name: git-branch
            value: $(tt.params.git-branch)
          - name: author
            value: $(tt.params.author)
    

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trggrt-pr-trigger-binding
  namespace: ferferfe
spec:
  params:
    - name: revision
      value: $(body.pull_request.head.ref)
    - name: repo-url
      value: github.com/$(body.repository.full_name).git
    - name: commit-sha
      value: $(body.pull_request.head.sha)
    - name: git-branch
      value: $(body.pull_request.head.ref)
    - name: submodules
      value: "false"
    - name: image-reference
      value: grewge
    - name: clone-dir
      value: $(body.repository.full_name)
 

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trggrt-pr-trigger-template
  namespace: ferferfe
spec:
  params:
    - name: revision
    - name: commit-sha
    - name: repo-url
    - name: image-reference
    - name: submodules
    - name: git-branch
    - name: clone-dir
  

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: trggrt-pr-trigger-run-
      spec:
        serviceAccountName: tekton-service-account
        pipelineRef:
          name: trggrt-pr-test-cases
        podTemplate:
          securityContext:
            fsGroup: 65532
        workspaces:
          - name: shared-data
            persistentVolumeClaim:
              claimName: tekton-pvc
          - name: github-secret
            secret:
              secretName: github-secret
          - name: docker-credentials
            secret:
              secretName: docker-credentials

        params:
          - name: repo-url
            value: $(tt.params.repo-url)
          - name: commit-sha
            value: $(tt.params.commit-sha)
          - name: revision
            value: $(tt.params.revision)
          - name: submodules
            value: $(tt.params.submodules)
          - name: git-branch
            value: $(tt.params.git-branch)
       
