apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kaniko-multi-repo
spec:
  description: | 
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to a registry
  params:
  - name: repo-url
    type: string
  - name: image-reference
    type: string
  - name: repo-url-1
    type: string
  - name: repo-url-2
    type: string
  - name: repo-url-3
    type: string

  workspaces:
  - name: shared-data
  - name: docker-credentials

  tasks:
  - name: clone-wda-server
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
  - name: clone-generator-tf-wdi
    runAfter: ["clone-wda-server"]
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url-1)
    - name: subdirectory
      value: generator-tf-wdi
  - name: clone-generator-jhipster
    runAfter: ["clone-wda-server","clone-generator-tf-wdi"]
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url-2)
    - name: subdirectory
      value: generator-jhipster
  - name: clone-jhipster-blueprints
    runAfter: ["clone-wda-server","clone-generator-tf-wdi","clone-generator-jhipster"]
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url-3)
    - name: subdirectory
      value: jhipster-blueprints
  - name: build-push-multi
    runAfter: ["clone-wda-server","clone-generator-tf-wdi","clone-generator-jhipster","clone-jhipster-blueprints"]
    taskRef:
      name: kaniko
    workspaces:
    - name: source
      workspace: shared-data
    - name: dockerconfig
      workspace: docker-credentials
    params:
    - name: IMAGE
      value: $(params.image-reference)
