apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy
  namespace: <%= projectName %>-namespace
spec:
  params:
  <%_ if (cloudProvider == "aws") { _%>
    - name: aws_access_key_id
      type: string
    - name: aws_secret_access_key
      type: string
    - name: region
      type: string
    - name: eks-cluster-name
      type: string
  <%_ } _%>
  <%_ if (cloudProvider == "azure") { _%>
    - name: azure-client-id
      type: string
    - name: azure-client-secret
      type: string
    - name: azure-tenant-id
      type: string
    - name: azure-subscription-id
      type: string
    - name: aks-cluster-name
      type: string
  <%_ } _%>
  <%_ if (cloudProvider == "minikube") { _%>
    - name: minikube-config-dir
      type: string
  <%_ } _%>
  workspaces:
    - name: source
  steps:
    <%_ if (cloudProvider == "aws") { _%>
    - name: setup-aws-credentials
      image: amazonlinux:2
      script: |
        #!/bin/bash
        echo "Setting up AWS credentials..."
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = $(params.aws-access-key-id)" >> ~/.aws/credentials
        echo "aws_secret_access_key = $(params.aws-secret-access-key)" >> ~/.aws/credentials
        echo "region = $(params.aws-region)" >> ~/.aws/config

    - name: deploy-to-eks
      image: bitnami/kubectl:latest
      script: |
        #!/bin/bash
        echo "Deploying to EKS..."
        cd /workspace/source/$(params.clone-dir)
        aws eks --region $(params.aws-region) update-kubeconfig --name $(params.eks-cluster-name)
        kubectl apply -f "yml files"
    <%_ } _%>

    <%_ if (cloudProvider == "azure") { _%>
    - name: setup-azure-credentials
      image: mcr.microsoft.com/azure-cli
      script: |
        #!/bin/bash
        echo "Setting up Azure credentials..."
        az account set --subscription $(params.azure-subscription-id)
        az ad sp create-for-rbac --name http://myApp --query password -o tsv > azure-credentials.txt
        AZURE_CLIENT_ID=$(params.azure-client-id) AZURE_CLIENT_SECRET=$(params.azure-client-secret) AZURE_TENANT_ID=$(params.azure-tenant-id)

    - name: deploy-to-aks
      image: bitnami/kubectl:latest
      script: |
        #!/bin/bash
        echo "Deploying to AKS..."
        cd /workspace/source/$(params.clone-dir)
        az aks get-credentials --resource-group $(params.azure-resource-group) --name $(params.aks-cluster-name)
        kubectl apply -f "yaml files"
    <%_ } _%>
    <%_ if (cloudProvider == "minikube") { _%>
    - name: deploy-to-minikube
      image: bitnami/kubectl:latest
      script: |
        #!/bin/bash
        echo "Deploying to Minikube..."
        export KUBECONFIG=$(params.minikube-config-dir)/kubeconfig
        cd /workspace/source/$(params.clone-dir)
        kubectl apply -f "yaml files"
    <%_ } _%>
  
