apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push-kaniko
  namespace: <%= projectName %>-namespace
spec:
  params:
    - name: clone-dir
      type: string
    - name: commit_sha
      type: string
    - name: image
      type: string 
  workspaces:
    - name: source
    - name: dockerconfig
    - name: cache-dir
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=./Dockerfile"
        - "--context=/workspace/source/$(params.clone-dir)/"
        - "--destination=$(params.image):$(params.commit_sha)"
        - "--cache=true"
        - "--cache-repo=$(params.image)"
        - "--cache-dir=/cache"
        - "--cache-run-layers"
        - "--cache-copy-layers"
  

