apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: upload-test-report-to-s3
  namespace: <%= namespaceName %>
spec:
  workspaces:
    - name: source
  params:
    - name: clone-dir
      type: string
    - name: AWS_ACCESS_KEY_ID
      type: string
    - name: AWS_SECRET_ACCESS_KEY
      type: string
    - name: AWS_SESSION_TOKEN
      type: string
    
  steps:
    - name: upload-to-s3
      image: amazon/aws-cli:latest
      script: |
        export AWS_ACCESS_KEY_ID=$(params.AWS_ACCESS_KEY_ID)
        export AWS_SECRET_ACCESS_KEY=$(params.AWS_SECRET_ACCESS_KEY)
        export AWS_SESSION_TOKEN=$(params.AWS_SESSION_TOKEN)
        export AWS_REGION='us-east-2'

        DATE_TIME=$(date '+%d.%m.%Y-%H:%M:%S')
        NEW_FILENAME="${DATE_TIME}-test-report.txt"
        cp /workspace/source/$(params.clone-dir)/test-report.txt /workspace/source/$(params.clone-dir)/${NEW_FILENAME}
        aws s3 cp /workspace/source/$(params.clone-dir)/${NEW_FILENAME} s3://tektontestbucket/${NEW_FILENAME}

  