apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: <%= pipelineName %>-trigger-binding 
  namespace: <%= projectName %>-namespace
spec:
  params:
  - name: revision
    value: $(body.head_commit.id)
  - name: repo-url
    value: <%= repoURL %>
  - name: submodules
    value: "false"
  - name: image-reference
    value: <%= imageRepositoryURL %>
  - name: maven-image-reference
    value: lokeshkarakala/custom-maven-image
  <%_ if (PathToPomFile == "Directory") { _%>
  - name: directory
    value: ./policies
  <%_ } _%>
  
---

apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: <%= pipelineName %>-trigger-template
  namespace: <%= projectName %>-namespace
spec:
  params:
  - name: revision
    default: <%= branch %>
  - name: maven-image-reference
  - name: repo-url
  - name: image-reference
  - name: submodules
  <%_ if (PathToPomFile == "Directory") { _%>
  - name: directory
  <%_ } _%>
  
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: <%= pipelineName %>-run-
      namespace: <%= projectName %>-namespace
    spec:
      serviceAccountName: <%= pipelineName %>-service-account
      pipelineRef:
        name: <%= pipelineName %>
      podTemplate:
        securityContext:
          fsGroup: 65532  
      workspaces:
      - name: shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
      - name: docker-credentials
        secret:
          secretName: docker-credentials
      <%_ if (repoType == "private") { _%>
      - name: ssh-creds
        secret:
          secretName: git-sshkey-secret
      <%_ } _%>
      
      params:
      - name: repo-url
        value: $(tt.params.repo-url)
      - name: revision
        value: $(tt.params.revision)
      - name: submodules
        value: $(tt.params.submodules)
      - name: image-reference
        value: $(tt.params.image-reference)
      - name: maven-image-reference
        value: $(tt.params.maven-image-reference)
      <%_ if (PathToPomFile == "Directory") { _%>
      - name: directory
        value: $(tt.params.directory)
      <%_ } _%>
      