apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cdk-deploy
  namespace: ferferfe
spec:
  params:
    - name: AWS_ACCESS_KEY_ID
      type: string
    - name: AWS_SECRET_ACCESS_KEY
      type: string
    - name: AWS_SESSION_TOKEN
  workspaces:
    - name: source
  steps:
    - name: deploy-cdk
      image: node:20.11
      script: |
        export IMAGE_TAG=$(params.commit_sha)
        export AWS_ACCESS_KEY_ID=$(params.AWS_ACCESS_KEY_ID)
        export AWS_SECRET_ACCESS_KEY=$(params.AWS_SECRET_ACCESS_KEY)
        export AWS_SESSION_TOKEN=$(params.AWS_SESSION_TOKEN)
        export AWS_REGION='us-east-2'

        aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

        kubectl apply -f "files directory path"
        
