apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy
  namespace: test-namespace
spec:
  params:
    - name: minikube-config-dir
      type: string
  workspaces:
    - name: source
  steps:

    - name: deploy-to-minikube
      image: bitnami/kubectl:latest
      script: |
        #!/bin/bash
        echo "Deploying to Minikube..."
        export KUBECONFIG=$(params.minikube-config-dir)/kubeconfig
        cd /workspace/source/$(params.clone-dir)
        kubectl apply -f "yaml files"
  
