apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: jkgkj-deploy
  namespace: eferg-namespace
spec:
  params:
    - name: aws_access_key_id
      type: string
    - name: aws_secret_access_key
      type: string
    - name: region
      type: string
    - name: eks-cluster-name
      type: string
  workspaces:
    - name: source
  steps:
    - name: setup-aws-credentials
      image: amazonlinux:2
      script: |
        #!/bin/bash
        echo "Setting up AWS credentials..."
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = $(params.aws-access-key-id)" >> ~/.aws/credentials
        echo "aws_secret_access_key = $(params.aws-secret-access-key)" >> ~/.aws/credentials
        echo "region = $(params.aws-region)" >> ~/.aws/config

    - name: deploy-to-eks
      image: bitnami/kubectl:latest
      script: |
        #!/bin/bash
        echo "Deploying to EKS..."
        cd /workspace/source/$(params.clone-dir)
        aws eks --region $(params.aws-region) update-kubeconfig --name $(params.eks-cluster-name)
        kubectl apply -f "yml files"

  
