apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: <%= namespaceName %>
data:
  secretToken: <%= githubPatToken %>
  
---

apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: <%= namespaceName %>
data:
  config.json: <%= dockerConfig %>