<%_ if (cloudProvider == "aws") { _%>
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
  fsType: ext4
<%_ } _%>
---
<%_ if (cloudProvider == "azure") { _%>
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk-sc
provisioner: disk.csi.azure.com
parameters:
  skuName: Standard_LRS # Options: Standard_LRS, Premium_LRS, StandardSSD_LRS
  storageaccounttype: Standard_LRS
reclaimPolicy: Retain # Options: Retain, Delete
volumeBindingMode: WaitForFirstConsumer
<%_ } _%>

