apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: <%= ProjectName %>-eventlistener
  namespace: <%= namespaceName %>
spec:
  resources:
    kubernetesResource:
      serviceType: LoadBalancer
  serviceAccountName: tekton-service-account
  triggers:
    - name: push-trigger
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "header.match('X-GitHub-Event', 'push') && body.repository.full_name && body.ref in ['refs/heads/development', 'refs/heads/qa', 'refs/heads/staging', 'refs/heads/master']"
      bindings:
        - ref: <%= componentName %>-push-trigger-binding
      template:
        ref: <%= componentName %>-push-trigger-template

    - name: pr-trigger
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["pull_request"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "header.match('X-GitHub-Event', 'pull_request') && body.repository.full_name  && body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - ref: <%= componentName %>-pr-trigger-binding
      template:
        ref: <%= componentName %>-pr-trigger-template

   