apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: go-pipeline
  namespace: test-namespace
spec:
  description: |
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to a registry
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
    - name: submodules
      type: string
    - name: image-reference
      type: string
    - name: git-branch
      type: string
    - name: author
      type: string
    - name: clone-dir
      type: string
    - name: image
      type: string
    - name: maven-image
      type: string
    

  workspaces:
    - name: github-secret
    - name: shared-data
    - name: docker-credentials
    - name: cache-dir
    
  tasks:
    - name: fetch-source
      taskRef:
        name: clone-repo
      workspaces:
        - name: source
          workspace: shared-data
        - name: github-secret
          workspace: github-secret
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
        - name: submodules
          value: $(params.submodules)
        - name: git-branch
          value: $(params.git-branch)
        - name: author
          vlaue: $(params.author)
       

    - name: test-cases
      onError: continue
      runAfter: ["fetch-source"]
      taskRef:
        name: cash-deposits-test-cases
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: clone-dir
          value: $(params.clone-dir)
        - name: git-branch
          value: $(params.git-branch)

    - name: get-commit-sha
      runAfter: ["fetch-source"]
      taskRef:
        name: get-commit-sha
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: clone-dir
          value: "$(params.clone-dir)"
    
    - name: build-push
      runAfter: ["get-commit-sha"]
      taskRef:
        name: build-and-push-kaniko
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: docker-credentials
        - name: cache-dir
          workspace: cache-dir
      params:
        - name: image
          value: $(params.image)
        - name: clone-dir
          value: "$(params.clone-dir)"
        - name: commit_sha
          value: "$(tasks.get-commit-sha.results.commit-sha)"
    

    - name: deploy
      runAfter: ["build-push"]
      workspaces:
        - name: source
          workspace: shared-data 
      taskRef:
        name: go-deploy
      params:
        - name: aws_access_key_id
          value: "$AWS_ACCESS_KEY_ID"
        - name: aws_secret_access_key
          value: "$AWS_SECRET_ACCESS_KEY"
        - name: region
          value: "$AWS_REGION"
        - name: eks-cluster-name
          value: test-cluster
       