<%_ if (repoType == "private") { _%>
apiVersion: v1
kind: Secret
metadata:
  name: git-sshkey-secret
  namespace: <%= projectName %>-namespace
data:
  id_rsa: <%= deployKey %>
  config: <%= sshConfig %>
<%_ } _%>
---

apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: <%= projectName %>-namespace
data:
  config.json: <%= dockerConfig %>