apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: eferg-namespace
data:
  secretToken: $TOKEN 
  
---

apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: eferg-namespace
data:
  config.json: $DOCKER_CONFIG