apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: ferferfe
data:
  secretToken: regewrge
  
---

apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: ferferfe
data:
  config.json: scdvzfsdv