apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: test-eventlistener
  namespace: test-namespace
spec:
  resources:
    kubernetesResource:
      serviceType: LoadBalancer
  serviceAccountName: tekton-service-account
  triggers:
    - name: push-trigger
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["push"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "header.match('X-GitHub-Event', 'push') && body.repository.full_name == '$GITHUB_USER_NAME/*'"
      bindings:
        - ref: spring,go-push-trigger-binding
      template:
        ref: spring,go-push-trigger-template

    - name: pr-trigger
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["pull_request"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "header.match('X-GitHub-Event', 'pull_request') && body.repository.full_name == '$GITHUB_USER_NAME/*' && body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - ref: spring,go-pr-trigger-binding
      template:
        ref: spring,go-pr-trigger-template

   